### ISSUE TITLE
VAD

### ISSUE THREAD

**Issue by JP199978** [BingYang-20/SRP-DNN#1]
Dear author, thanks for your sharing of code and the state-of-the-art performance of multiple moving sound source localization.
There is an issue in the Dataset.py folder: Unresolved reference 'VAD:1118'.
Did I miss something? How should I fix this issue? I look forward to your response.

**Comment by BingYang-20** [comment]
Thank you for bringing this to our attention. We have corrected line 1118 from VAD[cnt: ] = sensor_vad_ori[-1] to sensor_vad[cnt: ] = sensor_vad_ori[-1]. You can try again.
